// Generated by rust/wasm/gen_tests.py from wabt wat2wasm 1.0.34; do not edit by hand.
//
// Each test encodes a sequence of `Op`s and compares it with the function body
// that wat2wasm assembles from the equivalent WAT (shown in the comment).

use super::encoder::{BlockType, MemArg, Op, ValType};

fn encode(ops: &[Op]) -> Vec<u8> {
    let mut buf = Vec::new();
    for op in ops {
        op.encode(&mut buf);
    }
    Op::End.encode(&mut buf);
    buf
}

#[test]
fn unreachable() {
    // unreachable
    let ops = vec![Op::Unreachable];
    assert_eq!(encode(&ops), vec![0x00, 0x0b]);
}

#[test]
fn nop() {
    // nop
    let ops = vec![Op::Nop];
    assert_eq!(encode(&ops), vec![0x01, 0x0b]);
}

#[test]
fn block_empty() {
    // block end
    let ops = vec![Op::Block(BlockType::Empty), Op::End];
    assert_eq!(encode(&ops), vec![0x02, 0x40, 0x0b, 0x0b]);
}

#[test]
fn block_f64() {
    // block (result f64) f64.const 1 end
    let ops = vec![Op::Block(BlockType::Value(ValType::F64)), Op::F64Const(1.0), Op::End];
    assert_eq!(encode(&ops), vec![0x02, 0x7c, 0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x3f, 0x0b, 0x0b]);
}

#[test]
fn loop_br_if() {
    // loop local.get 0 br_if 0 end
    let ops = vec![Op::Loop(BlockType::Empty), Op::LocalGet(0), Op::BrIf(0), Op::End];
    assert_eq!(encode(&ops), vec![0x03, 0x40, 0x20, 0x00, 0x0d, 0x00, 0x0b, 0x0b]);
}

#[test]
fn if_else() {
    // local.get 0 if nop else nop end
    let ops = vec![Op::LocalGet(0), Op::If(BlockType::Empty), Op::Nop, Op::Else, Op::Nop, Op::End];
    assert_eq!(encode(&ops), vec![0x20, 0x00, 0x04, 0x40, 0x01, 0x05, 0x01, 0x0b, 0x0b]);
}

#[test]
fn if_i32() {
    // local.get 0 if (result i32) i32.const 1 else i32.const 2 end
    let ops = vec![Op::LocalGet(0), Op::If(BlockType::Value(ValType::I32)), Op::I32Const(1), Op::Else, Op::I32Const(2), Op::End];
    assert_eq!(encode(&ops), vec![0x20, 0x00, 0x04, 0x7f, 0x41, 0x01, 0x05, 0x41, 0x02, 0x0b, 0x0b]);
}

#[test]
fn br() {
    // block br 0 end
    let ops = vec![Op::Block(BlockType::Empty), Op::Br(0), Op::End];
    assert_eq!(encode(&ops), vec![0x02, 0x40, 0x0c, 0x00, 0x0b, 0x0b]);
}

#[test]
fn br_table() {
    // block block block local.get 0 br_table 0 1 2 end end end
    let ops = vec![Op::Block(BlockType::Empty), Op::Block(BlockType::Empty), Op::Block(BlockType::Empty), Op::LocalGet(0), Op::BrTable(vec![0, 1], 2), Op::End, Op::End, Op::End];
    assert_eq!(encode(&ops), vec![0x02, 0x40, 0x02, 0x40, 0x02, 0x40, 0x20, 0x00, 0x0e, 0x02, 0x00, 0x01, 0x02, 0x0b, 0x0b, 0x0b, 0x0b]);
}

#[test]
fn return_() {
    // i32.const 0 return
    let ops = vec![Op::I32Const(0), Op::Return];
    assert_eq!(encode(&ops), vec![0x41, 0x00, 0x0f, 0x0b]);
}

#[test]
fn drop_select() {
    // f64.const 1 drop f64.const 1 f64.const 2 local.get 0 select
    let ops = vec![Op::F64Const(1.0), Op::Drop, Op::F64Const(1.0), Op::F64Const(2.0), Op::LocalGet(0), Op::Select];
    assert_eq!(encode(&ops), vec![0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x3f, 0x1a, 0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x3f, 0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x20, 0x00, 0x1b, 0x0b]);
}

#[test]
fn locals() {
    // local.get 1 local.set 0 local.get 0 local.tee 1 drop
    let ops = vec![Op::LocalGet(1), Op::LocalSet(0), Op::LocalGet(0), Op::LocalTee(1), Op::Drop];
    assert_eq!(encode(&ops), vec![0x20, 0x01, 0x21, 0x00, 0x20, 0x00, 0x22, 0x01, 0x1a, 0x0b]);
}

#[test]
fn local_index_128() {
    // local.get 128 local.set 127
    let ops = vec![Op::LocalGet(128), Op::LocalSet(127)];
    assert_eq!(encode(&ops), vec![0x20, 0x80, 0x01, 0x21, 0x7f, 0x0b]);
}

#[test]
fn globals() {
    // global.get 0 global.set 0
    let ops = vec![Op::GlobalGet(0), Op::GlobalSet(0)];
    assert_eq!(encode(&ops), vec![0x23, 0x00, 0x24, 0x00, 0x0b]);
}

#[test]
fn i32_load_store() {
    // i32.const 0 i32.const 0 i32.load i32.store offset=4
    let ops = vec![Op::I32Const(0), Op::I32Const(0), Op::I32Load(MemArg::i32(0)), Op::I32Store(MemArg::i32(4))];
    assert_eq!(encode(&ops), vec![0x41, 0x00, 0x41, 0x00, 0x28, 0x02, 0x00, 0x36, 0x02, 0x04, 0x0b]);
}

#[test]
fn i64_load_store() {
    // i32.const 0 i32.const 8 i64.load i64.store offset=16
    let ops = vec![Op::I32Const(0), Op::I32Const(8), Op::I64Load(MemArg::f64(0)), Op::I64Store(MemArg::f64(16))];
    assert_eq!(encode(&ops), vec![0x41, 0x00, 0x41, 0x08, 0x29, 0x03, 0x00, 0x37, 0x03, 0x10, 0x0b]);
}

#[test]
fn f64_load_store() {
    // i32.const 0 i32.const 0 f64.load offset=8 f64.store offset=128
    let ops = vec![Op::I32Const(0), Op::I32Const(0), Op::F64Load(MemArg::f64(8)), Op::F64Store(MemArg::f64(128))];
    assert_eq!(encode(&ops), vec![0x41, 0x00, 0x41, 0x00, 0x2b, 0x03, 0x08, 0x39, 0x03, 0x80, 0x01, 0x0b]);
}

#[test]
fn f64_load_offset_65536() {
    // i32.const 0 f64.load offset=65536
    let ops = vec![Op::I32Const(0), Op::F64Load(MemArg::f64(65536))];
    assert_eq!(encode(&ops), vec![0x41, 0x00, 0x2b, 0x03, 0x80, 0x80, 0x04, 0x0b]);
}

#[test]
fn i32_const_edges() {
    // i32.const 0 drop i32.const 63 drop i32.const 64 drop i32.const -64 drop i32.const -65 drop i32.const 2147483647 drop i32.const -2147483648 drop
    let ops = vec![Op::I32Const(0), Op::Drop, Op::I32Const(63), Op::Drop, Op::I32Const(64), Op::Drop, Op::I32Const(-64), Op::Drop, Op::I32Const(-65), Op::Drop, Op::I32Const(i32::MAX), Op::Drop, Op::I32Const(i32::MIN), Op::Drop];
    assert_eq!(encode(&ops), vec![0x41, 0x00, 0x1a, 0x41, 0x3f, 0x1a, 0x41, 0xc0, 0x00, 0x1a, 0x41, 0x40, 0x1a, 0x41, 0xbf, 0x7f, 0x1a, 0x41, 0xff, 0xff, 0xff, 0xff, 0x07, 0x1a, 0x41, 0x80, 0x80, 0x80, 0x80, 0x78, 0x1a, 0x0b]);
}

#[test]
fn i64_const_edges() {
    // i64.const -1 drop i64.const 9223372036854775807 drop i64.const -9223372036854775808 drop
    let ops = vec![Op::I64Const(-1), Op::Drop, Op::I64Const(i64::MAX), Op::Drop, Op::I64Const(i64::MIN), Op::Drop];
    assert_eq!(encode(&ops), vec![0x42, 0x7f, 0x1a, 0x42, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0x00, 0x1a, 0x42, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x80, 0x7f, 0x1a, 0x0b]);
}

#[test]
fn f64_const() {
    // f64.const 0 drop f64.const -0 drop f64.const 3.141592653589793 drop f64.const inf drop
    let ops = vec![Op::F64Const(0.0), Op::Drop, Op::F64Const(-0.0), Op::Drop, Op::F64Const(std::f64::consts::PI), Op::Drop, Op::F64Const(f64::INFINITY), Op::Drop];
    assert_eq!(encode(&ops), vec![0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x1a, 0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x1a, 0x44, 0x18, 0x2d, 0x44, 0x54, 0xfb, 0x21, 0x09, 0x40, 0x1a, 0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x7f, 0x1a, 0x0b]);
}

#[test]
fn i32_compare() {
    // local.get 0 local.get 1 i32.eq drop local.get 0 local.get 1 i32.ne drop local.get 0 local.get 1 i32.lt_s drop local.get 0 local.get 1 i32.lt_u drop local.get 0 local.get 1 i32.gt_s drop local.get 0 local.get 1 i32.gt_u drop local.get 0 local.get 1 i32.le_s drop local.get 0 local.get 1 i32.le_u drop local.get 0 local.get 1 i32.ge_s drop local.get 0 local.get 1 i32.ge_u drop local.get 0 i32.eqz drop
    let ops = vec![Op::LocalGet(0), Op::LocalGet(1), Op::I32Eq, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32Ne, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32LtS, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32LtU, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32GtS, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32GtU, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32LeS, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32LeU, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32GeS, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32GeU, Op::Drop, Op::LocalGet(0), Op::I32Eqz, Op::Drop];
    assert_eq!(encode(&ops), vec![0x20, 0x00, 0x20, 0x01, 0x46, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x47, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x48, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x49, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x4a, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x4b, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x4c, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x4d, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x4e, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x4f, 0x1a, 0x20, 0x00, 0x45, 0x1a, 0x0b]);
}

#[test]
fn i32_arith() {
    // local.get 0 local.get 1 i32.add drop local.get 0 local.get 1 i32.sub drop local.get 0 local.get 1 i32.mul drop local.get 0 local.get 1 i32.and drop local.get 0 local.get 1 i32.shl drop
    let ops = vec![Op::LocalGet(0), Op::LocalGet(1), Op::I32Add, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32Sub, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32Mul, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32And, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I32Shl, Op::Drop];
    assert_eq!(encode(&ops), vec![0x20, 0x00, 0x20, 0x01, 0x6a, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x6b, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x6c, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x71, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x74, 0x1a, 0x0b]);
}

#[test]
fn i64_ops() {
    // local.get 0 local.get 1 i64.sub drop local.get 0 local.get 1 i64.and drop local.get 0 local.get 1 i64.or drop local.get 0 local.get 1 i64.xor drop local.get 0 i64.eqz drop
    let ops = vec![Op::LocalGet(0), Op::LocalGet(1), Op::I64Sub, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I64And, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I64Or, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::I64Xor, Op::Drop, Op::LocalGet(0), Op::I64Eqz, Op::Drop];
    assert_eq!(encode(&ops), vec![0x20, 0x00, 0x20, 0x01, 0x7d, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x83, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x84, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x85, 0x1a, 0x20, 0x00, 0x50, 0x1a, 0x0b]);
}

#[test]
fn f64_compare() {
    // local.get 0 local.get 1 f64.eq drop local.get 0 local.get 1 f64.ne drop local.get 0 local.get 1 f64.lt drop local.get 0 local.get 1 f64.gt drop local.get 0 local.get 1 f64.le drop local.get 0 local.get 1 f64.ge drop
    let ops = vec![Op::LocalGet(0), Op::LocalGet(1), Op::F64Eq, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Ne, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Lt, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Gt, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Le, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Ge, Op::Drop];
    assert_eq!(encode(&ops), vec![0x20, 0x00, 0x20, 0x01, 0x61, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x62, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x63, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x64, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x65, 0x1a, 0x20, 0x00, 0x20, 0x01, 0x66, 0x1a, 0x0b]);
}

#[test]
fn f64_unary() {
    // local.get 0 f64.abs drop local.get 0 f64.neg drop local.get 0 f64.ceil drop local.get 0 f64.floor drop local.get 0 f64.trunc drop local.get 0 f64.nearest drop local.get 0 f64.sqrt drop
    let ops = vec![Op::LocalGet(0), Op::F64Abs, Op::Drop, Op::LocalGet(0), Op::F64Neg, Op::Drop, Op::LocalGet(0), Op::F64Ceil, Op::Drop, Op::LocalGet(0), Op::F64Floor, Op::Drop, Op::LocalGet(0), Op::F64Trunc, Op::Drop, Op::LocalGet(0), Op::F64Nearest, Op::Drop, Op::LocalGet(0), Op::F64Sqrt, Op::Drop];
    assert_eq!(encode(&ops), vec![0x20, 0x00, 0x99, 0x1a, 0x20, 0x00, 0x9a, 0x1a, 0x20, 0x00, 0x9b, 0x1a, 0x20, 0x00, 0x9c, 0x1a, 0x20, 0x00, 0x9d, 0x1a, 0x20, 0x00, 0x9e, 0x1a, 0x20, 0x00, 0x9f, 0x1a, 0x0b]);
}

#[test]
fn f64_binary() {
    // local.get 0 local.get 1 f64.add drop local.get 0 local.get 1 f64.sub drop local.get 0 local.get 1 f64.mul drop local.get 0 local.get 1 f64.div drop local.get 0 local.get 1 f64.min drop local.get 0 local.get 1 f64.max drop local.get 0 local.get 1 f64.copysign drop
    let ops = vec![Op::LocalGet(0), Op::LocalGet(1), Op::F64Add, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Sub, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Mul, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Div, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Min, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Max, Op::Drop, Op::LocalGet(0), Op::LocalGet(1), Op::F64Copysign, Op::Drop];
    assert_eq!(encode(&ops), vec![0x20, 0x00, 0x20, 0x01, 0xa0, 0x1a, 0x20, 0x00, 0x20, 0x01, 0xa1, 0x1a, 0x20, 0x00, 0x20, 0x01, 0xa2, 0x1a, 0x20, 0x00, 0x20, 0x01, 0xa3, 0x1a, 0x20, 0x00, 0x20, 0x01, 0xa4, 0x1a, 0x20, 0x00, 0x20, 0x01, 0xa5, 0x1a, 0x20, 0x00, 0x20, 0x01, 0xa6, 0x1a, 0x0b]);
}

#[test]
fn conversions() {
    // local.get 0 i64.extend_i32_u drop local.get 1 i64.reinterpret_f64 f64.reinterpret_i64 drop
    let ops = vec![Op::LocalGet(0), Op::I64ExtendI32U, Op::Drop, Op::LocalGet(1), Op::I64ReinterpretF64, Op::F64ReinterpretI64, Op::Drop];
    assert_eq!(encode(&ops), vec![0x20, 0x00, 0xad, 0x1a, 0x20, 0x01, 0xbd, 0xbf, 0x1a, 0x0b]);
}

#[test]
fn call() {
    // f64.const 1 call 0 drop
    let ops = vec![Op::F64Const(1.0), Op::Call(0), Op::Drop];
    assert_eq!(encode(&ops), vec![0x44, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x3f, 0x10, 0x00, 0x1a, 0x0b]);
}
