// The C header written next to an object file: sizes, the memory layout, and the
// prototypes of the kernels (usable from C and C++).

use super::{Arch, Format, Target};

pub struct HeaderInfo<'a> {
    pub name: &'a str,
    pub target: Target,
    pub count_states: usize,
    pub count_obs: usize,
    pub count_params: usize,
    pub count_diffs: usize,
    pub mem_size: usize,
    pub complex: bool,
    pub fast: bool,
    /// a Composer/Symbolica model: inputs are the parameters, outputs go to `mem`
    pub symbolica: bool,
    /// the instruction set the kernels need, e.g. "AVX and FMA (x86-64-v3)"
    pub cpu: &'a str,
    /// the C math library functions the kernels call
    pub imports: &'a [String],
    pub version: &'a str,
}

pub fn header(h: &HeaderInfo) -> String {
    let n = h.name;
    let up = n.to_uppercase();
    let format = match h.target.format {
        Format::Elf => "ELF",
        Format::MachO => "Mach-O",
    };
    let arch = match h.target.arch {
        Arch::X86_64 => "x86-64",
    };
    let values = if h.complex {
        "Counts are in doubles: complex values are (re, im) pairs."
    } else {
        "All values are doubles."
    };

    let usage = if h.symbolica {
        format!(
            "   Inputs are the parameters and outputs are written to `mem`:\n\
             \n\
             \x20      double inputs[{up}_COUNT_PARAMS], outs[{up}_COUNT_OBS];\n\
             \x20      int status = {n}(outs, NULL, 0, inputs);    // 0 on success\n"
        )
    } else {
        format!(
            "   Direct mode, one point: `mem` holds the states ({up}_COUNT_STATES), then the outputs\n\
             \x20  ({up}_COUNT_OBS){diffs}; `params` the parameters ({up}_COUNT_PARAMS, or NULL if none).\n\
             \n\
             \x20      double mem[{up}_MEM_SIZE] = {{0}};\n\
             \x20      // write the states to mem[0 .. {up}_COUNT_STATES - 1], then\n\
             \x20      int status = {n}(mem, NULL, 0, params);    // 0 on success\n\
             \x20      // and read the outputs from mem[{up}_COUNT_STATES ...]\n\
             \n\
             \x20  Indirect mode, many points: `states` points to {up}_COUNT_STATES + {up}_COUNT_OBS\n\
             \x20  arrays (states, then outputs); {n}(NULL, states, i, params) reads element i of each\n\
             \x20  state array and writes element i of each output array.\n",
            diffs = if h.count_diffs > 0 {
                format!(", then the derivatives ({up}_COUNT_DIFFS)")
            } else {
                String::new()
            }
        )
    };

    let mut s = String::new();
    s += &format!(
        "/* {n}.h: the kernels in {n}.o ({arch} {format}), generated by symjit {version}.\n\
         \n\
         \x20  {values}\n\
         \n\
         {usage}\
         \n\
         \x20  The code uses {cpu} instructions. {calls}\n\
         */\n\n",
        version = h.version,
        cpu = h.cpu,
        calls = if h.imports.is_empty() {
            "It calls no library functions.".to_string()
        } else {
            format!("It calls {} from the C math library: link with -lm.", h.imports.join(", "))
        },
    );
    s += &format!("#ifndef SYMJIT_{up}_H\n#define SYMJIT_{up}_H\n\n#include <stddef.h>\n\n");
    s += "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n";
    s += &format!("#define {up}_COUNT_STATES {}\n", h.count_states);
    s += &format!("#define {up}_COUNT_OBS {}\n", h.count_obs);
    s += &format!("#define {up}_COUNT_PARAMS {}\n", h.count_params);
    if h.count_diffs > 0 {
        s += &format!("#define {up}_COUNT_DIFFS {}\n", h.count_diffs);
    }
    s += &format!("#define {up}_MEM_SIZE {}\n\n", h.mem_size);
    s += "#ifndef SYMJIT_SLICE_DEFINED\n#define SYMJIT_SLICE_DEFINED\n";
    s += "/* an array of doubles (indirect mode) */\n";
    s += "typedef struct {\n    double *ptr;\n    size_t len;\n} symjit_slice;\n#endif\n\n";
    s += &format!(
        "int {n}(double *mem, const symjit_slice *states, size_t idx, const double *params);\n"
    );
    if h.fast {
        let args: Vec<String> = (0..h.count_states).map(|i| format!("double x{}", i)).collect();
        s += &format!("\n/* the single output at one point */\ndouble {n}_fast({});\n", args.join(", "));
    }
    s += "\n#ifdef __cplusplus\n}\n#endif\n\n";
    s += &format!("#endif /* SYMJIT_{up}_H */\n");
    s
}
