"""Disassembler for the machine code generated by Symjit.

>>> from sympy import symbols
>>> from symjit import compile_func, disassemble
>>> x, y = symbols("x y")
>>> f = compile_func([x, y], [x * y + 1.0])
>>> disassemble(f)            # the scalar kernel
>>> disassemble(f, "simd")    # the SIMD kernel used for vectorized calls
"""

import os
import platform
import re
import shutil
import struct
import subprocess
import sys
import tempfile

from .func import Func, FuncComplex, SymbolicaFunc

__all__ = ["disassemble", "disassembly"]

KERNELS = ("scalar", "simd", "fast", "bytecode")

# architecture -> (objdump `-m` name, extra objdump options, tools to try)
_OBJDUMP = {
    "x86_64": ("i386:x86-64", ["-M", "intel"], ["objdump"]),
    "aarch64": ("aarch64", [], ["aarch64-linux-gnu-objdump", "aarch64-none-elf-objdump", "objdump"]),
    "riscv64": ("riscv:rv64", [], ["riscv64-linux-gnu-objdump", "riscv64-unknown-elf-objdump", "objdump"]),
}

_LINE = re.compile(r"^\s*([0-9a-f]+):\t((?:[0-9a-f]{2} ?)+)\s*\t?(.*)$")


def _compiler_of(f):
    """Returns the `RustyCompiler` behind a Func, FuncComplex, or SymbolicaFunc."""
    if isinstance(f, SymbolicaFunc):
        c = f.complex_compiler if f.is_complex else f.compiler
    elif isinstance(f, (Func, FuncComplex)):
        c = f.compiler
    else:
        raise TypeError(
            f"cannot disassemble an object of type {type(f).__name__}; "
            "expected Func, FuncComplex, or SymbolicaFunc"
        )

    if c is None:
        raise ValueError("the function has no compiled code")

    return c


def _architecture(ty):
    """Maps the `ty` option of the compiler to an architecture name."""
    if ty in ("native", "debug"):
        machine = platform.machine().lower()
        if machine in ("x86_64", "amd64"):
            return "x86_64"
        if machine in ("aarch64", "arm64"):
            return "aarch64"
        if machine.startswith("riscv64"):
            return "riscv64"
        raise RuntimeError(f"unsupported processor: {machine}")
    if ty.startswith("amd"):
        return "x86_64"
    if ty == "arm":
        return "aarch64"
    if ty == "riscv":
        return "riscv64"
    raise ValueError(f"the compiler type `{ty}` does not generate machine code")


def _machine_code(compiler, kernel):
    """Dumps the raw bytes of `kernel` (or the text of the bytecode)."""
    fd, path = tempfile.mkstemp(prefix="symjit_dump_", suffix=".bin")
    os.close(fd)

    try:
        try:
            compiler.dump(path, what=kernel)
        except ValueError:
            raise ValueError(f"the `{kernel}` kernel is not available for this function") from None
        with open(path, "rb") as fd:
            return fd.read()
    finally:
        if os.path.exists(path):
            os.remove(path)


def _find_objdump(arch):
    """Finds an objdump that understands `arch`, or returns None."""
    machine = _OBJDUMP[arch][0]

    with tempfile.TemporaryDirectory() as d:
        name = os.path.join(d, "probe.bin")
        with open(name, "wb") as fd:
            fd.write(b"\0" * 4)

        for tool in _OBJDUMP[arch][2]:
            path = shutil.which(tool)
            if path is None:
                continue
            try:
                # a build without support for `machine` fails on the -m option
                probe = subprocess.run(
                    [path, "-D", "-b", "binary", "-m", machine, name], capture_output=True, text=True
                )
            except OSError:
                continue
            if probe.returncode == 0:
                return path

    return None


def _run_objdump(path, arch, code):
    machine, options, _ = _OBJDUMP[arch]

    with tempfile.TemporaryDirectory() as d:
        name = os.path.join(d, "code.bin")
        with open(name, "wb") as fd:
            fd.write(code)

        # -z: do not skip runs of zeros, --insn-width: do not wrap long instructions
        cmd = [path, "-D", "-z", "--insn-width=16", "-b", "binary", "-m", machine, *options, name]
        out = subprocess.run(cmd, capture_output=True, text=True, check=True).stdout

    records = []
    for line in out.splitlines():
        m = _LINE.match(line)
        if m:
            raw = bytes.fromhex(m.group(2).replace(" ", ""))
            records.append((int(m.group(1), 16), raw, " ".join(m.group(3).split())))
    return records


def _run_capstone(arch, code):
    try:
        import capstone
    except ImportError:
        return None

    arch_mode = {
        "x86_64": (capstone.CS_ARCH_X86, capstone.CS_MODE_64),
        "aarch64": (capstone.CS_ARCH_ARM64, capstone.CS_MODE_ARM),
        "riscv64": (getattr(capstone, "CS_ARCH_RISCV", None), getattr(capstone, "CS_MODE_RISCV64", None)),
    }[arch]

    if arch_mode[0] is None:
        return None

    cs = capstone.Cs(*arch_mode)
    records = []
    pos = 0

    while pos < len(code):
        ins = next(cs.disasm(code[pos:], pos, count=1), None)
        if ins is None:  # undecodable: emit one word/byte of data and resync
            step = 4 if arch != "x86_64" else 1
            step = min(step, len(code) - pos)
            records.append((pos, code[pos : pos + step], "(bad)" if arch == "x86_64" else ".word"))
            pos += step
        else:
            records.append((ins.address, bytes(ins.bytes), f"{ins.mnemonic} {ins.op_str}".strip()))
            pos += ins.size

    return records


def _x86_data_target(address, size, text):
    """The address read or written by a RIP-relative instruction (not `lea`), if any."""
    if text.startswith("lea"):
        return None

    m = re.search(r"#\s*0x([0-9a-f]+)", text)  # objdump adds the target as a comment
    if m:
        return int(m.group(1), 16)

    m = re.search(r"\[rip\s*([+-])\s*(0x[0-9a-f]+|\d+)\]", text)  # capstone
    if m:
        disp = int(m.group(2), 0)
        return address + size + (disp if m.group(1) == "+" else -disp)

    return None


def _split_code_data(records, arch):
    """Splits the listing into code and the trailing constant pool.

    The pool follows the last function (`ret`) and holds constants and function
    pointers; decoding it as instructions would only print noise. On x86-64 the
    start of the pool is the lowest address read through a RIP-relative operand.
    On the other architectures (and if no such operand exists) the code ends at
    the last `ret`.
    """
    rets = [i for i, (_, _, text) in enumerate(records) if text.split(" ")[0] == "ret" or text.startswith("ret")]

    if not rets:
        return records, []

    end = rets[-1]

    if arch == "x86_64":
        targets = [t for a, r, x in records if (t := _x86_data_target(a, len(r), x)) is not None]
        if targets:
            pool = min(targets)
            before = [i for i in rets if records[i][0] < pool]
            if before:
                end = before[-1]

    return records[: end + 1], records[end + 1 :]


def _format_data(data, code_end, size):
    lines = [f"; constant pool, {size - code_end} bytes at offset {code_end:#x} (not disassembled)"]
    raw = b"".join(r for _, r, _ in data)
    base = data[0][0] if data else code_end

    pad = min(-base % 8, len(raw))  # the pool is 8-byte aligned; skip the alignment padding
    if pad:
        lines.append(f"{base:6x}:  {raw[:pad].hex(' ')}  (padding)")

    for i in range(pad, len(raw) - (len(raw) - pad) % 8, 8):
        chunk = raw[i : i + 8]
        (u,) = struct.unpack("<Q", chunk)
        (d,) = struct.unpack("<d", chunk)
        note = f"    ; {d!r}" if d == 0.0 or 1e-300 < abs(d) < 1e300 else ""
        lines.append(f"{base + i:6x}:  {chunk.hex(' ')}  .quad {u:#018x}{note}")

    tail = (len(raw) - pad) % 8
    if tail:
        lines.append(f"{base + len(raw) - tail:6x}:  {raw[-tail:].hex(' ')}")

    return lines


def disassembly(f, kernel="scalar", tool="auto", show_data=False):
    """Returns the disassembled machine code of a compiled Symjit function as a string.

    See `disassemble` for the parameters.
    """
    if kernel not in KERNELS:
        raise ValueError(f"kernel should be one of {KERNELS}, not `{kernel}`")
    if tool not in ("auto", "objdump", "capstone"):
        raise ValueError("tool should be `auto`, `objdump`, or `capstone`")

    compiler = _compiler_of(f)

    if kernel == "bytecode":
        return _machine_code(compiler, "bytecode").decode("utf8", errors="replace")

    arch = _architecture(compiler.ty)
    code = _machine_code(compiler, kernel)

    records = None
    used = None

    if tool in ("auto", "objdump"):
        path = _find_objdump(arch)
        if path is not None:
            records, used = _run_objdump(path, arch, code), os.path.basename(path)
        elif tool == "objdump":
            raise RuntimeError(f"no objdump supporting {arch} was found")

    if records is None:
        records, used = _run_capstone(arch, code), "capstone"
        if records is None:
            raise RuntimeError(
                f"cannot disassemble {arch} code: install binutils objdump with {arch} support "
                "or the `capstone` Python package (`pip install capstone`)"
            )

    body, data = _split_code_data(records, arch)
    code_end = body[-1][0] + len(body[-1][1]) if body else 0

    width = max((len(r) for _, r, _ in body), default=1) * 3
    out = [f"; symjit `{kernel}` kernel, {arch}, {len(code)} bytes ({code_end} of code), disassembled with {used}"]
    out += [f"{a:6x}:  {r.hex(' '):<{width}s}  {text}" for a, r, text in body]

    if data:
        if show_data:
            out += _format_data(data, code_end, len(code))
        else:
            out.append(f"; constant pool, {len(code) - code_end} bytes at offset {code_end:#x} (use show_data=True to list)")

    return "\n".join(out)


def disassemble(f, kernel="scalar", tool="auto", show_data=False, file=None):
    """Prints the disassembled machine code of a compiled Symjit function.

    Parameters
    ==========

    f: a compiled function, i.e., a `Func`, `FuncComplex`, or `SymbolicaFunc` object.
    kernel (default `scalar`): the kernel to disassemble.
        * "scalar": the kernel used for scalar (single-point) calls.
        * "simd": the SIMD kernel used for vectorized calls on arrays.
        * "fast": the fast (packed complex) kernel, if the function has one.
        * "bytecode": prints the intermediate bytecode instead of machine code.
    tool (default `auto`): the disassembler. `objdump` uses the GNU binutils objdump,
        `capstone` uses the Python capstone package, and `auto` prefers objdump when
        it supports the target architecture and falls back to capstone.
    show_data (default `False`): also lists the constant pool that follows the code.
    file (default `None`): the stream to print to (`sys.stdout` if `None`).

    The machine code is followed by a constant pool (floating-point constants and
    function pointers), which is not disassembled.

    >>> from sympy import symbols
    >>> from symjit import compile_func, disassemble
    >>> x, y = symbols("x y")
    >>> f = compile_func([x, y], [x * y + 1.0])
    >>> disassemble(f, "simd")
    """
    print(disassembly(f, kernel=kernel, tool=tool, show_data=show_data), file=file or sys.stdout)
