"""The comparison of run.py on the n-loop Symbolica evaluators (examples/symbolica/run_nloop.py).

    python nloop.py 1            # the 1-loop evaluator (1loop_instructions_2.txt)
    python nloop.py 1 2          # 1- and 2-loop
    python nloop.py 2 -m 200     # 200 random sample points (default 1000)

As in run_nloop.py, the instruction streams are read from examples/symbolica/<n>loop_instructions_2.txt
(no Symbolica needed) and compiled as complex evaluators with the options of
examples/symbolica/symjit.toml. Then:

    A   f.write_obj("out/loop<n>_a", dtype="complex128")     symjit's native code generator
    B   ty="wasm" -> out/loop<n>_b.wasm -> wasm2c -> cc -c   symjit's WebAssembly backend + wasm2c + C compiler

A generated C driver (out/loop<n>_bench.c) evaluates the same random complex sample points with
both objects (`loop<n>_a(outs, NULL, 0, inputs)` and `w2c_loop<n>wasm_run(instance, outs, 0, 0,
inputs)`, one call per point), checks them against symjit's JIT and reports the time per
evaluation; the JIT's own time (`evaluate_complex` on all points, from Python) is shown too.

Mind the size of B: the 2-loop module translates to 19 MB of C in one function, which gcc -O2
compiles in about a minute with about 3 GB of memory (CFLAGS=-O1 is faster). The 3-loop
evaluator has no B: symjit refuses WebAssembly functions above 7,654,321 bytes (the limit of
JavaScript hosts), and its code is 9.9 MB; only A is built and timed.

Needs what run.py needs: symjit with the `wasm` and `obj` features, wasm2c and its runtime, a C
compiler (CC, CFLAGS as in run.py).
"""

import argparse
import os
import re
import sys
import time

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import run as common  # noqa: E402  (helpers of run.py)

from symjit import compile_evaluator  # noqa: E402

SYMBOLICA = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "symbolica")
CONFIG = os.path.join(SYMBOLICA, "symjit.toml")
OUT = common.OUT

DRIVER = r"""/* generated by nloop.py: evaluates {name}_a.o and {name}_b.o at the same points */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "{name}_a.h"
{b_include}

#define NP {NAME}_A_COUNT_PARAMS   /* doubles: (re, im) pairs */
#define NO {NAME}_A_COUNT_OBS
#define MEM {NAME}_A_MEM_SIZE

static double now(void) {{
    struct timespec t;
    clock_gettime(CLOCK_MONOTONIC, &t);
    return t.tv_sec + 1e-9 * t.tv_nsec;
}}

static size_t m;
static double *inputs, *out_a, *out_b;

static void pass_a(void) {{
    double mem[MEM + 1];
    for (size_t s = 0; s < m; s++) {{
        {name}_a(mem, NULL, 0, inputs + NP * s);
        memcpy(out_a + NO * s, mem, NO * sizeof(double));
    }}
}}

#if {has_b}
static w2c_{name}wasm inst;
static wasm_rt_memory_t *wmem;
static u32 w_out, w_in;

static void pass_b(void) {{
    for (size_t s = 0; s < m; s++) {{
        if (w2c_{name}wasm_run(&inst, w_out, 0, 0, w_in + (u32)(8 * NP * s)) != 0) {{
            fprintf(stderr, "run failed\n");
            exit(1);
        }}
        memcpy(out_b + NO * s, wmem->data + w_out, NO * sizeof(double));
    }}
}}
#endif

static double best(void (*pass)(void), int samples, double target) {{
    pass();
    double b = 1e300;
    for (int k = 0; k < samples; k++) {{
        int reps = 0;
        double t0 = now(), t;
        do {{
            pass();
            reps++;
            t = now() - t0;
        }} while (t < target);
        if (t / reps < b) b = t / reps;
    }}
    return b;
}}

int main(int argc, char **argv) {{
    if (argc < 3) return 2;
    m = (size_t)atol(argv[1]);
    inputs = malloc(m * NP * sizeof(double));
    out_a = calloc(m * NO, sizeof(double));
    out_b = calloc(m * NO, sizeof(double));
    FILE *fd = fopen(argv[2], "rb");
    if (fread(inputs, sizeof(double), m * NP, fd) != m * NP) return 3;
    fclose(fd);

    printf("a %.6g\n", 1e9 * best(pass_a, 5, 0.2) / m);
#if {has_b}
    /* the module's memory: the outputs at __heap_base, then all the inputs */
    wasm_rt_init();
    wasm2c_{name}wasm_instantiate(&inst);
    wmem = w2c_{name}wasm_memory(&inst);
    w_out = *w2c_{name}wasm_0x5F_heap_base(&inst);
    w_in = (w_out + 8 * (MEM + 1) + 15) & ~15u;
    uint64_t need = (uint64_t)w_in + 8ull * NP * m;
    if (need > wmem->size) wasm_rt_grow_memory(wmem, (need - wmem->size + 65535) / 65536);
    memcpy(wmem->data + w_in, inputs, 8 * NP * m);
    printf("b %.6g\n", 1e9 * best(pass_b, 5, 0.2) / m);
#endif

    char path[4096];
    snprintf(path, sizeof path, "%s.a", argv[2]);
    fd = fopen(path, "wb");
    fwrite(out_a, sizeof(double), m * NO, fd);
    fclose(fd);
#if {has_b}
    snprintf(path, sizeof path, "%s.b", argv[2]);
    fd = fopen(path, "wb");
    fwrite(out_b, sizeof(double), m * NO, fd);
    fclose(fd);
    wasm2c_{name}wasm_free(&inst);
    wasm_rt_free();
#endif
    return 0;
}}
"""


def build_b(name, evaluator, include):
    """B, or None if symjit cannot build the module (the 3-loop evaluator is too large)"""
    base = os.path.join(OUT, f"{name}_b")
    t0 = time.perf_counter()
    try:
        g = compile_evaluator(evaluator, dtype="complex128", ty="wasm")
        g.dump(base + ".wasm", "wasm", dtype="complex128")
    except ValueError as e:
        print(f"  B: {str(e).strip()}")
        return None
    t1 = time.perf_counter()
    common.run(["wasm2c", base + ".wasm", "-o", base + ".c", "-n", f"{name}wasm"])
    t2 = time.perf_counter()
    with open(base + ".h") as fd:
        imports = re.findall(r"/\* import: 'symjit' '(\w+)' \*/", fd.read())
    if imports:
        sys.exit(f"{name}: the module imports {imports}; this example handles import-free evaluators only")
    print(f"  B: compiling {os.path.getsize(base + '.c') / 1e6:.1f} MB of C ...", flush=True)
    common.run([common.CC, *common.CFLAGS, "-Wno-unused-function", "-Wno-unused-variable", "-I", include,
                "-c", base + ".c", "-o", base + ".o"])
    t3 = time.perf_counter()
    return 1e3 * (t1 - t0), 1e3 * (t2 - t1), 1e3 * (t3 - t2)


def relative(got, want):
    """max |got - want| / max |want| over the sample points (0.0 if bitwise equal)"""
    if np.array_equal(got, want):
        return 0.0
    return float(np.max(np.abs(got - want)) / np.max(np.abs(want)))


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("loops", nargs="+", choices=["1", "2", "3"], help="1, 2 and/or 3")
    parser.add_argument("-m", type=int, default=1000, help="sample points (default 1000)")
    args = parser.parse_args()

    runtime, include = common.wasm2c_runtime()
    os.makedirs(OUT, exist_ok=True)
    rt = os.path.join(OUT, "wasm-rt-impl.o")
    common.run([common.CC, *common.CFLAGS, "-I", include, "-c", os.path.join(runtime, "wasm-rt-impl.c"), "-o", rt])

    rows = []
    for loops in args.loops:
        name = f"loop{loops}"
        print(f"{loops}-loop evaluator", flush=True)
        with open(os.path.join(SYMBOLICA, f"{loops}loop_instructions_2.txt"), encoding="utf-8") as fd:
            evaluator = fd.read()

        t0 = time.perf_counter()
        f = compile_evaluator(evaluator, dtype="complex128", ty=CONFIG)  # as run_nloop.py
        n = f.complex_compiler.count_params // 2
        rng = np.random.default_rng(1337)
        samples = rng.random((args.m, n)) + 1j * rng.random((args.m, n))
        jit = f.evaluate_complex(samples)  # also compiles
        ms_jit = 1e3 * (time.perf_counter() - t0)

        t0 = time.perf_counter()
        f.write_obj(os.path.join(OUT, f"{name}_a"), dtype="complex128")
        ms_a = 1e3 * (time.perf_counter() - t0)
        ms_b = build_b(name, evaluator, include)

        inputs = os.path.join(OUT, f"{name}.in")
        samples.astype(np.complex128).tofile(inputs)
        src = os.path.join(OUT, f"{name}_bench.c")
        with open(src, "w") as fd:
            fd.write(DRIVER.format(name=name, NAME=name.upper(), has_b=int(ms_b is not None),
                                   b_include=f'#include "{name}_b.h"' if ms_b else ""))
        exe = os.path.join(OUT, f"{name}_bench")
        objs = [os.path.join(OUT, f"{name}_a.o")] + ([os.path.join(OUT, f"{name}_b.o"), rt] if ms_b else [])
        common.run([common.CC, *common.CFLAGS, "-I", OUT, "-I", include, src, *objs, "-lm", "-o", exe])
        times = dict(line.split() for line in common.run([exe, str(args.m), inputs]).splitlines())

        # the JIT, evaluating all the points in one call from Python
        best = float("inf")
        for _ in range(5):
            t0 = time.perf_counter()
            f.evaluate_complex(samples)
            best = min(best, time.perf_counter() - t0)

        no = f.complex_compiler.count_obs // 2
        a = np.fromfile(inputs + ".a").view(np.complex128).reshape(args.m, no)
        b = np.fromfile(inputs + ".b").view(np.complex128).reshape(args.m, no) if ms_b else None
        rows.append(dict(loops=loops, n=n, jit=1e9 * best / args.m, a=float(times["a"]),
                         b=float(times["b"]) if ms_b else None, ms_jit=ms_jit, ms_a=ms_a, ms_b=ms_b,
                         a_jit=relative(a, jit), b_jit=relative(b, jit) if ms_b else None,
                         a_b=relative(a, b) if ms_b else None,
                         size_a=os.path.getsize(os.path.join(OUT, f"{name}_a.o")),
                         size_b=os.path.getsize(os.path.join(OUT, f"{name}_b.o")) if ms_b else None))

    print(f"\n{common.CC} {' '.join(common.CFLAGS)}, {args.m} complex sample points; A with {CONFIG.split(os.sep)[-1]}"
          f" options; times per evaluation\n")
    head = (f"{'loops':5s} {'inputs':>6s}  {'JIT (batch)':>11s} {'A':>9s} {'B':>9s} {'B/A':>6s}  {'A vs B':>8s} "
            f"{'A vs JIT':>8s}  {'A .o':>7s} {'B .o':>7s}  {'build A':>8s} {'build B':>20s}")
    print(head)
    print("-" * len(head))
    us = lambda v: "-" if v is None else f"{v / 1e3:7.2f}us"
    ok = True
    for r in rows:
        rb = "-" if r["b"] is None else f"{r['b'] / r['a']:5.2f}x"
        ab = "-" if r["a_b"] is None else ("identical" if r["a_b"] == 0 else f"{r['a_b']:.1e}")
        aj = "identical" if r["a_jit"] == 0 else f"{r['a_jit']:.1e}"
        steps_b = "-" if r["ms_b"] is None else "+".join(f"{v / 1e3:.2f}" for v in r["ms_b"]) + " s"
        size_b = "-" if r["size_b"] is None else f"{r['size_b'] / 1e6:.1f}MB"
        print(f"{r['loops']:>5s} {r['n']:6d}  {us(r['jit']):>11s} {us(r['a']):>9s} {us(r['b']):>9s} {rb:>6s}  "
              f"{ab:>8s} {aj:>8s}  {r['size_a'] / 1e6:5.1f}MB {size_b:>7s}  {r['ms_a']:5.0f} ms {steps_b:>20s}")
        ok = ok and r["a_jit"] < 1e-12 and (r["b_jit"] is None or r["b_jit"] < 1e-12)
    print("\nJIT (batch) = evaluate_complex on all the points from Python, per point; differences are relative "
          "to the largest output;\nbuild B = symjit to .wasm + wasm2c + C compiler")
    if not ok:
        sys.exit("A or B differs from the JIT")


if __name__ == "__main__":
    main()
